### ISSUE TITLE
Test on retrained model have errors !

### ISSUE THREAD

**Issue by welen-zhou** [GeeeG/CloudAAE#4]
Hi，Ge
   I have trained a model follow by your Train a network script : python train_cloudAAE_ycbv.py . and I have success training a model. but when i test the model use  evaluate_cloudAAE_ycbv.py script , have a errors happen : 
    
   NFO - 2021-08-15 15:36:03,823 - tf_logging - Restoring parameters from trained_network/20210731-231714/model.ckpt
2021-08-15 15:36:03.885536: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key dgcnn1/bn/6d_pose/dgcnn1/bn/moments/Squeeze/ExponentialMovingAverage not found in checkpoint
Traceback (most recent call last):
  File "/root/anaconda3/envs/caae/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/root/anaconda3/envs/caae/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/anaconda3/envs/caae/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key dgcnn1/bn/6d_pose/dgcnn1/bn/moments/Squeeze/ExponentialMovingAverage not found in checkpoint
         [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
         [[{{node save/RestoreV2/_53}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_75_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

what does this cause? How to fixed the problem . and wish your reply . thanks !

**Comment by ghost** [comment]
Same issue here. Did u figure it out?

**Comment by ghost** [comment]
I fixed it myself, in cloudAAE/evaluate_cloudAAE_ycbv.py change "6d_pose" scope name to "decoder".
